=== olegflo/jvalid/out/production/jvalid/com/goodness/jvalid/tests/schemas/schema.json
{
    "$schema":"http://json-schema.org/draft-03/schema",
    "type":"object",
    "properties":{
        "current_page":{
            "type":"integer",
            "required":true,
            "minimum":1
        },
        "per_page":{
            "type":"integer",
            "required":true,
            "minimum":1,
            "maximum":100
        },
        "total_entries":{
            "type":"integer",
            "required":true,
            "minimum":1
        },
        "items":{
            "type":"array",
            "items":{
                "type":"object",
                "required":true,
                "$ref":"innerSchema.json",
                "minItems":1
            }
        }
    }
}

=== olegflo/jvalid/src/com/goodness/jvalid/tests/schemas/data.json
{
    "current_page":1,
    "per_page":10,
    "total_entries":3,
    "items":[
        {
            "user":{
                "id":9843,
                "owner_id":739,
                "full_name":"qbsdk",
                "email":"oleg@quickblox.com",
                "login":"qbsdk",
                "phone":null,
                "website":null,
                "created_at":"2012-08-12T11:10:24Z",
                "updated_at":"2012-10-03T11:16:32Z",
                "last_request_at":"2012-10-03T11:16:32Z",
                "external_user_id":null,
                "facebook_id":null,
                "twitter_id":null,
                "blob_id":null,
                "user_tags":"car, cat"
            }
        },
        {
            "user":{
                "id":14842,
                "owner_id":739,
                "full_name":"Afanasy Gribanov",
                "email":"yurlov@gmail.com",
                "login":"yurlov",
                "phone":null,
                "website":null,
                "created_at":"2012-10-03T11:16:53Z",
                "updated_at":"2012-10-03T11:16:53Z",
                "last_request_at":null,
                "external_user_id":null,
                "facebook_id":null,
                "twitter_id":null,
                "blob_id":null,
                "user_tags":null
            }
        },
        {
            "user":{
                "id":14843,
                "owner_id":739,
                "full_name":"Mirogod Buzinsky",
                "email":"zheglov@gmail.com",
                "login":"zheglov",
                "phone":null,
                "website":null,
                "created_at":"2012-10-03T11:16:54Z",
                "updated_at":"2012-10-03T11:16:54Z",
                "last_request_at":null,
                "external_user_id":null,
                "facebook_id":null,
                "twitter_id":null,
                "blob_id":null,
                "user_tags":null
            }
        }
    ]
}
